from __future__ import annotations

import os

from .probe import Stream, audio_streams, sub_streams


# ── Internal helpers ──────────────────────────────────────────────────────────

def _stream_comments(streams: list[Stream]) -> list[str]:
    lines = []
    for i, s in enumerate(audio_streams(streams), start=1):
        ch = f"{s.channels}ch" if s.channels else ""
        ttl = f" / {s.title}" if s.title else ""
        lines.append(
            f"#   Audio [{i}] {s.codec_name.upper()} {ch} lang={s.language}{ttl}")
    for i, s in enumerate(sub_streams(streams), start=1):
        ttl = f" / {s.title}" if s.title else ""
        lines.append(f"#   Sub   [{i}] {s.codec_name} lang={s.language}{ttl}")
    return lines


def _header(mode: str, show: str, season: str, source: str, streams: list[Stream]) -> list[str]:
    return [
        "#!/bin/bash",
        f"# Generated by batchbrake ({mode} mode)",
        f"# Show   : {show}",
        f"# Season : {season}",
        f"# Source : {source}",
        "# Streams:",
        *_stream_comments(streams),
    ]


def _audio_flags(streams: list[Stream]) -> tuple[str, str]:
    """Return (track_list, encoder_list) for HandBrake -a / --aencoder."""
    audio = audio_streams(streams)
    tracks = ",".join(str(i + 1) for i in range(len(audio)))
    encoders = ",".join(["copy"] * len(audio))
    return tracks, encoders


def _sub_flags(streams: list[Stream], subtitle_default: int | None = None) -> tuple[str, str]:
    """Return (track_list, default_flag) for HandBrake -s / --subtitle-default."""
    subs = sub_streams(streams)
    tracks = ",".join(str(i + 1) for i in range(len(subs)))
    default = f"--subtitle-default {subtitle_default}" if subtitle_default else ""
    return tracks, default


def _encode_flags(quality: int, preset: str, force_crop: bool,
                  a_tracks: str, a_enc: str, s_tracks: str, s_default: str) -> str:
    """Build the common HandBrake flag block (everything after -i / -o / --chapters)."""
    crop = "--crop 0:0:0:0" if force_crop else "# crop: HandBrake auto-detect"
    lines = [
        f"    --encoder x265 --quality {quality} --encoder-preset {preset} \\"]
    if a_tracks:
        lines.append(f"    -a {a_tracks} --aencoder {a_enc} \\")
    if s_tracks:
        lines.append(f"    -s {s_tracks} \\")
        if s_default:
            lines.append(f"    {s_default} \\")
    lines.append(f"    {crop} \\")
    lines.append(f"    --markers --decomb")
    return "\n".join(lines)


# ── Public generators ─────────────────────────────────────────────────────────

def generate_disc_script(
    episodes: list,
    streams: list[Stream],
    input_path: str,
    show: str,
    season: str,
    quality: int,
    preset: str,
    force_crop: bool,
    output_dir: str,
    hb_cmd: str,
) -> str:
    a_tracks, a_enc = _audio_flags(streams)
    s_tracks, _ = _sub_flags(streams)   # disc mode never sets subtitle-default
    flags = _encode_flags(quality, preset, force_crop,
                          a_tracks, a_enc, s_tracks, "")

    lines = _header("disc", show, season, input_path, streams) + [
        "",
        f'input="{input_path}"',
        f'show="{show}"',
        f'season="{season}"',
        f'output_dir="{output_dir}"',
        "",
        'mkdir -p "$output_dir/$show"',
        "",
    ]

    for ep in episodes:
        ep_str = f"{ep.number:02d}"
        out = f'"$output_dir/$show/$show - S{season}E{ep_str}.mkv"'
        lines.append(
            f"# Episode {ep_str} — chapters {ep.chapter_start}–{ep.chapter_end} ({ep.duration_str()})")
        lines.append(
            f"{hb_cmd} \\\n"
            f'    -i "$input" \\\n'
            f"    -o {out} \\\n"
            f"    --chapters {ep.chapter_start}-{ep.chapter_end} \\\n"
            f"{flags}"
        )
        lines.append("")

    return "\n".join(lines)


def generate_bulk_script(
    episodes: list,
    streams: list[Stream],
    subtitle_default: int | None,
    show: str,
    season: str,
    quality: int,
    preset: str,
    force_crop: bool,
    output_dir: str,
    hb_cmd: str,
) -> str:
    a_tracks, a_enc = _audio_flags(streams)
    s_tracks, s_default = _sub_flags(streams, subtitle_default)
    flags = _encode_flags(quality, preset, force_crop,
                          a_tracks, a_enc, s_tracks, s_default)

    source_dir = os.path.dirname(episodes[0].path) if episodes else "unknown"
    lines = _header("bulk", show, season, source_dir, streams) + [
        "",
        f'show="{show}"',
        f'season="{season}"',
        f'output_dir="{output_dir}"',
        "",
        'mkdir -p "$output_dir/$show"',
        "",
    ]

    for ep in episodes:
        ep_str = f"{ep.episode_number:02d}"
        out = f'"$output_dir/$show/$show - S{season}E{ep_str}.mkv"'
        lines.append(f"# Episode {ep_str} — {ep.filename}")
        lines.append(
            f"{hb_cmd} \\\n"
            f'    -i "{ep.path}" \\\n'
            f"    -o {out} \\\n"
            f"{flags}"
        )
        lines.append("")

    return "\n".join(lines)
